function layers = cnnFocal()
    layers = [
        image3dInputLayer([64 64 64 1],"Name","image3dinput")
        convolution3dLayer([3 3 3],32,"Name","conv3d","Padding","same")
        batchNormalizationLayer("Name","batchnorm")
        reluLayer("Name","relu")
        maxPooling3dLayer([5 5 5],"Name","maxpool3d","Padding","same","Stride",[2 2 2])
        convolution3dLayer([3 3 3],64,"Name","conv3d_1","Padding","same")
        batchNormalizationLayer("Name","batchnorm_1")
        reluLayer("Name","relu_1")
        maxPooling3dLayer([5 5 5],"Name","maxpool3d_1","Padding","same","Stride",[2 2 2])
        convolution3dLayer([3 3 3],128,"Name","conv3d_2","Padding","same")
        batchNormalizationLayer("Name","batchnorm_2")
        reluLayer("Name","relu_2")
        transposedConv3dLayer([3 3 3],128,"Name","transposed-conv3d","Cropping","same","Stride",[2 2 2])
        convolution3dLayer([3 3 3],64,"Name","conv3d_3","Padding","same")
        batchNormalizationLayer("Name","batchnorm_3")
        reluLayer("Name","relu_3")
        transposedConv3dLayer([3 3 3],64,"Name","transposed-conv3d_1","Cropping","same","Stride",[2 2 2])
        convolution3dLayer([3 3 3],32,"Name","conv3d_4","Padding","same")
        batchNormalizationLayer("Name","batchnorm_4")
        reluLayer("Name","relu_4")
        transposedConv3dLayer([3 3 3],32,"Name","transposed-conv3d_2","Cropping","same","Stride",[2 2 2])
        convolution3dLayer([3 3 3],16,"Name","conv3d_5","Padding","same")
        batchNormalizationLayer("Name","batchnorm_5")
        reluLayer("Name","relu_5")
        transposedConv3dLayer([3 3 3],16,"Name","transposed-conv3d_3","Cropping","same","Stride",[2 2 2])
        convolution3dLayer([3 3 3],8,"Name","conv3d_6","Padding","same")
        batchNormalizationLayer("Name","batchnorm_6")
        reluLayer("Name","relu_6")
        transposedConv3dLayer([3 3 3],8,"Name","transposed-conv3d_4","Cropping","same","Stride",[2 2 1])
        convolution3dLayer([3 3 3],4,"Name","conv3d_7","Padding","same")
        batchNormalizationLayer("Name","batchnorm_7")
        reluLayer("Name","relu_7")
        convolution3dLayer([3 3 3],2,"Name","conv3d_8","Padding","same")
        sigmoidLayer("Name","sigmoid")
        focalLossLayer("Name","focal-loss")];
    
    % plot(layerGraph(layers));
end
