name: DL-SMLFM
channels:
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - cudatoolkit=11.8
  - cudnn
  - torchaudio
  - pytorch-cuda=11.8
  - torchvision
  - pytorch
  - scipy
  - tensorboard
  - tifffile
  - scikit-image
  - opencv
