
function [] = main()
    % any file we want save will store in foldpath
    foldpath = "generated";
    if exist(foldpath, 'dir'), rmdir("generated", 's'); end
    mkdir(foldpath);
    
    % set parameters for generating sample
    basic_paras(foldpath);
    sample_paras(foldpath);
    
    % generating sample
    ds = dataloader(2^13, foldpath);
end

%% Set parameters for generating sample

function [] = basic_paras(foldpath)
    paras = [];
    
    % dimensional parameters that need to consider memory
    paras.NumMolecule = 64;             % big affect on running time
    paras.NumFrame    = 4;
    paras.DimFrame    = [128, 128, 64]; % row-column-(depth); yx(z)
    paras.UpSampling  = [8, 8, 8];
    paras.BitDepth    = 'uint16';  
    
    % parameters that adjust distribution of sample parameters
    paras.PixelSize   = [65, 65, 100];  % use to correct the covariance
    paras.MaxStd      = 2;              % adjust covariance of moleculars
    paras.LumRange    = [128, double(intmax(paras.BitDepth))];
    paras.AppearRange = [1/8, 1/1];     % min, max % of moleculars/frame
    
    % parameters for further processing
    paras.noise_mu  = 0;
    paras.noise_var = 1/256;

    % others
    % if SaveTif is true, each section will creat a subfold to store the
    % .tif of frames that the section generates, for illustration purposes
    % only. 
    paras.SaveTif = false;   

    save(fullfile(foldpath, "paras.mat"), "paras")
end

function [] = sample_paras(foldpath)
    % Descriptions:
    % - This function will use basic parameters to randomly generate 
    %   sample parameters that used to generate sample. 
    % - Basic parameters can help us generate sample with same 
    %   distribution but not exatly same. To save a dataset, sample 
    %   parameters generated by this function need to be saved so that we
    %   do not need to save the save to save memeory and avoid I/O
    %   performance.
    % Rules:
    % - Every parameters will save in .mat file in 'foldpath.' We load 
    %   all basic parameters needed at begining and save all the sample
    %   parameters at the end of function. We won't access or modity the
    %   .mat file during function.
    % - When generting parameters, we use double and do not round the
    %   data. We will do all the dtype change or round the float at the 
    %   end of function, when saving parameter. 
    % Output:
    %   (D stands for number of dimensions, i.e., length(DimFrame))
    % - mu_set    [D * NumMolecule]           double  non-rounded
    % - cov_set   [D * D * NumMolecule]       double  non-rounded
    % - lum_set   [NumMolecule]               double  non-rounded
    % - mask_set  [NumFrame * NumMolecule]    logical

    % load the basic parameters we will use
    load(fullfile(foldpath, "paras.mat"), "paras");
    NumMolecule = paras.NumMolecule;
    NumFrame    = paras.NumFrame; 
    DimFrame    = paras.DimFrame;
    PixelSize   = paras.PixelSize;
    MaxStd      = paras.MaxStd;
    LumRange    = paras.LumRange;
    AppearRange = paras.AppearRange;

    D = length(DimFrame);  % number of dimensions

    % 1. mu set, [D * NumMolecule]
    mu_set = (DimFrame-1)' .* rand([D, NumMolecule]) + 1;

    % 2. covariance set, [D * D * NumMolecule]
    cov_set = zeros(D, D, NumMolecule);
    % pixel size correction
    MaxStd = MaxStd * (PixelSize(1) ./ PixelSize);
    for n = 1:NumMolecule
        cov_set(:, :, n) = diag((MaxStd.^2) .* rand([1, D]));
    end
    
    % 3. luminance set, [NumMolecule]
    lum_set = (LumRange(2) - LumRange(1)) * rand([1, NumMolecule]);
    lum_set = lum_set + LumRange(1);
    
    % 4. mask set, [NumFrame, NumMolecule]
    % determine how many moleculars will appear in each frame
    NumRange = round(NumMolecule * AppearRange);
    num_appear_set = randi(NumRange, [NumFrame, 1]);
    % create a mask stands which moleculars will appear in each frame
    mask_set = zeros(NumFrame, NumMolecule);
    for n = 1:NumFrame
        index = randperm(NumMolecule, num_appear_set(n));
        mask_set(n, index) = 1;  % mask of a molecular is 1 if appear
    end

    % save sample parameters in 'paras,' change dtype/rounded meantime
    paras.mu_set    = mu_set;
    paras.cov_set   = cov_set;
    paras.lum_set   = lum_set;
    paras.mask_set  = logical(mask_set);
    save(fullfile(foldpath, "paras.mat"), "paras")
end
