ds = dataloader;
model = unet;

options = trainingOptions('adam', ...
    'MaxEpochs',40, ...
    'MiniBatchSize',1, ...
    'InitialLearnRate',1e-4, ...
    'Shuffle','every-epoch', ...
    'Plots','training-progress', ...
    'Verbose',true);

net = trainNetwork(ds, model, options);
