sampleGenerator;
[trainData, valData] = dataloader;
model = unet;

if exist(mfilename, 'dir') == false, mkdir(mfilename); end

options = trainingOptions('adam', ...
    'MaxEpochs', 40, ...
    'MiniBatchSize', 2, ...
    'InitialLearnRate', 1e-4, ...
    'LearnRateSchedule', 'piecewise', ...
    'LearnRateDropFactor', 0.1000, ...
    'LearnRateDropPeriod', 5, ...
    'Shuffle','every-epoch', ...
    'ValidationData', valData, ...
    'ValidationFrequency', 100, ...
    'CheckpointPath', mfilename, ...
    'Plots', 'training-progress', ...
    'Verbose', true);

net = trainNetwork(trainData, model, options);
